{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "snmpd-secret" }}
  labels:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    helm.sh/chart: {{ include "snmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  snmpd.conf: |
{{ (.Files.Get "snmpd/snmpd.conf") | indent 4 }}
{{ .Values.configmap.user_conf | indent 4 }}
    sysDescr {{ .Values.configmap.system_description }}
    sysContact {{ .Values.configmap.system_contact }}
    sysName {{ .Values.configmap.system_name }}
    sysLocation {{ .Values.configmap.system_location }}
  fm.conf: |
    sql_connection={{ .Values.configmap.connection }}
{{- end }}
