apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    helm.sh/chart: {{ include "snmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: port-snmp
      port: 161
      protocol: UDP
      targetPort: 161
      nodePort: {{ .Values.service.nodePorts.snmp }}
    - name: port-agentx
      port: 705
      protocol: TCP
      targetPort: 705
      nodePort: {{ .Values.service.nodePorts.agentx }}
    - name: port-trap
      port: 162
      protocol: TCP
      targetPort: 162
      nodePort: {{ .Values.service.nodePorts.trap }}

  selector:
    app.kubernetes.io/name: {{ include "snmp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
