---
- project:
    check:
      jobs:
        - k8sapp-snmp-armada-tox-linters
        - k8app-snmp-armada-tox-py39
        - k8sapp-snmp-armada-tox-pylint
        - k8sapp-snmp-armada-tox-flake8
        - k8sapp-snmp-armada-tox-metadata
        - k8sapp-snmp-armada-tox-coverage
        - k8sapp-snmp-armada-tox-security
        - k8sapp-snmp-armada-tox-coverage-c
    gate:
      jobs:
        - k8sapp-snmp-armada-tox-linters
        - k8app-snmp-armada-tox-py39
        - k8sapp-snmp-armada-tox-pylint
        - k8sapp-snmp-armada-tox-flake8
        - k8sapp-snmp-armada-tox-metadata
        - k8sapp-snmp-armada-tox-coverage
        - k8sapp-snmp-armada-tox-security
        - k8sapp-snmp-armada-tox-coverage-c
    post:
      jobs:
        - stx-snmp-armada-app-upload-git-mirror

- job:
    name: k8sapp-snmp-armada-tox-linters
    parent: openstack-tox-linters
    description: |
      Run linters for snmp-armada-app
    nodeset: debian-bullseye
    post-run: python3-k8sapp-snmp/k8sapp_snmp/k8sapp_snmp/tests/playbooks/upload-linter-reports.yaml

- job:
    name: k8app-snmp-armada-tox-py39
    parent: openstack-tox-py39
    description: |
        Run py39 test for k8app-snmp-armada-app
    nodeset: debian-bullseye
    required-projects:
        - starlingx/config
        - starlingx/fault
        - starlingx/utilities
        - starlingx/root
    files:
        - python3-k8sapp-snmp/k8sapp_snmp/*
    vars:
        tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
        tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-snmp-armada-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp_snmp
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-snmp/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-snmp-armada-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp_snmp
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-snmp/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-snmp-armada-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp_snmp
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-snmp-armada-tox-coverage
    parent: tox
    description: |
      Run coverage analysis for k8sapp_snmp
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-snmp/*
    vars:
      tox_envlist: coverage
      tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'
    post-run: python3-k8sapp-snmp/k8sapp_snmp/k8sapp_snmp/tests/playbooks/upload-coverage-reports.yaml

- job:
    name: k8sapp-snmp-armada-tox-security
    parent: tox
    description: |
      Run security analysis for k8sapp_snmp
    nodeset: debian-bullseye
    required-projects:
      - starlingx/root
    files:
      - python3-k8sapp-snmp/*
    vars:
      tox_envlist: security
      tox_extra_args: -c python3-k8sapp-snmp/k8sapp_snmp/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'
    post-run: python3-k8sapp-snmp/k8sapp_snmp/k8sapp_snmp/tests/playbooks/upload-security-reports.yaml

- job:
    name: k8sapp-snmp-armada-tox-coverage-c
    parent: tox
    description: |
      Run C/C++ coverage analysis via gcov/lcov
    nodeset: debian-bullseye
    vars:
      tox_envlist: coverage-c
    post-run: python3-k8sapp-snmp/k8sapp_snmp/k8sapp_snmp/tests/playbooks/upload-coverage-reports.yaml

- job:
    name: stx-snmp-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/snmp-armada-app to
      github.com/starlingx/snmp-armada-app
    vars:
      git_mirror_repository: starlingx/snmp-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-snmp-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-snmp-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - lUluJlUOnGfxcDgSQwC1nz0mdogo6MQ70tlR8diTuqHCp1Se+zOJ59eBVZWPi3q5VY0e2
          uVS9dZ1iNfVh0rnX6a33UjF+vPk65IuXV8SRlHA6NITHLxJmgqPVDg2A5a3ENK6Q9Z0zE
          EqtyMCsOCfbG1d2zWySeAyrGEen598xYe7aXSWxpuYqo/vCgRqRfc5oCi8WvRCAJF7p7R
          VbpilT+7cTE9zNju0u85sW+gFkl2vfVsZpg3ipjsu3t6zu2Apbzgk9V3gs8LJLV+6oVbW
          aVtcr0HrG0V8vOS9PD6x4E+/eX86sASi8WEOFy9AQo81C82W7TMM49/5CWOZxGmqNiDY7
          ZSwFc7cMmGkZWRa/X0kyg4d9Yhutzpih5x77Il8Nthh62cz93PcfVTpZwgOK59o2sevVk
          Ei+mKx1dBVpQ1JL59OzbftshpjDjgvlHpiLupTLxY0eYh61vXXpgdYK+YRxouuTilplfc
          PG6gCLZ+JQ/Cr3I9i05av6EUxrO1YLyqNyvlUYIjv0fuHxwHquYt4MFPhLh2FpilMdFf4
          NJdjkd2OHowhoXcHU+Z+F5Y7kYBE9TDXSbr61i3Q4Fq+mR1VKe4psEeHOhMmZ1/4CFSCI
          PwV8CXGolGZa08bs/YYU7aZAHGzGsmSvZ4DhplPqp1WpoV7aLxdw/WTuVuHHN0=
        - kZXMG2vWSmeCWg8AMbNoHYq+rOn3lGDVaoL7PTFAt7le0U5DB5Z/aZ8d5N7UqTXRosN+X
          SWb5edAAVYaCvjm5MYRdGnCaX5i7ilGyh6TKo2NC1ufIRH3enFCrEBfzEcEUIYbAFJaQB
          xXfite1tJAoQ5xLEahvhp1OIPh0aQ8eOITF57+mfI6OPN1NqXfunJjeIbD0y/1idOHEJz
          7yL0uxvxkk+eNGwCdtqsxAUwEmvtgwDSA6ESU9XZnZ+AW1y4vwhIInJL4qRbhx5SuESEb
          +sBm6qjzlglzLriCVQkid0euE0F6RPuyJldQsEiU3NwxMgkLGGKd7nV0+kjeW5eaxrwli
          PoWFM/olzKisRTDC0gu5cfqzrBLzE7U9h6ZCi28CJlqTF+//b7ILx2sYAQgLo9JhVLeif
          Jlb7Rv2kjhqwG3PJcTK8LrE6RTaRJ6sfopCsLlP2RM17Zen2zPx4vzScs5QPuYvy+wbAF
          EJ5q3IVB6oUqgy6GpSGYDE5U9ZbABTNwXhKDuLn2ZK2WQRCyWWi5577tHp+fxAKl7EznS
          oXCm2iuV8AsMjb5viqur6mEg9sn7pcDdvizpSmeGwbVFZjdSH14u/x+SQZyf5MbaM6l+U
          RixWDnYkzZIKezN7qc+7x7f3ggHndm5tkvdgogsGuafPvr4/q24d3AtbVpstn8=
        - dm+9QPXZvgGzdxy1TRWfxviUP8mgO9ZTAd3Hvr35yiFX49idYa7wsGeU3p/FpJu7/4lbg
          G5jbGbxlJgbvIsxUCQ6eTPvLOtlHaz6dJ9hTlDa9Zd+K93sgVSFu7f4hDTZAMDKmbrupD
          6CZnRHGCXwvYxuPvEOZuuUWnDG8oucVwAGa74r5/kwKoBG7PyeNhHA1DOIM4QxXkyOKd2
          4M7FzN0YchSUZgPSJoiKKOfvv/6bhvkeL4K7YTju9NNCMEdpUpmWRolu0gb2C4F3oh/I0
          OTT07ePXxm+PBbWqgnIFmNXHtK5zKSen87At2Xn5KqURM9KkQ4V+h8W0dHH/r/lA0ugIa
          eolyDuk8uhpCFAFH64SY1sidm1B4EYPLspL6Ox0nkmSzXh0WCDtHEn5pGYCp2/ZEn4DOI
          5pe/1QXThqCy2kGniHVpIeR+v753/22GaC6ieYjNu/LVPTS8A4bv//y2u+UVxvuijSgPa
          0nvRXh3JovI4sc42C7G61P/Rter1xODPOxpOvOEOBTnl5psNqwPaUkaBhJrZLY0QYb2KY
          Pal2TFJmz1DxtW1UNSnrfeNgRrjGfsgXJuR/PWzS3Sb4sFsNxZagYoe0dSGdyCBUhh8vc
          kjud9nbb/1sHiwvmI3tGOEVxyBPKVDVfYVQB1XfH84RM3H7Jl86bgblpyDHdwE=
        - AvkYTEY/ogfByGmvQCBilcJVxSqyJ/mHUafiYfk5krFz/nxo9NNreQFXx2d3KEvSXsY3F
          pDOEGiIm2GU4nnKgP4Z+dBzCT5wWxxPVEh137ZdxizoFdXOw9G+XFupDrTZ9FB3iPA9DY
          YSCkN7uryG6p1px/pdLLp98JLlu6HLLvNguYepC3bNbh0VXUa6rFxcFOX4kka0ERfuy5a
          rt+AmYlEgNh4NNv5jkHW/J3r1X6E1VVA9WfUI6yvNMd+mtzk7KRkiXVdZEOsIglY/pq/X
          U0kmTq0eEdNyKNYVq6BE0Gt5j5mpbvSHv1slWfFE4pVb5CNNt9mFaI+qrodcClNk1gj/9
          1+J9cW12GRl5B3hoOm+vDaj32rKKGlD8QofFJnMjjV8dMs5atSY5jdHdYUMf4sSdcuKg+
          RJIvzPLI/zGyxhOzGM10xFAyJhrwamerQjxGiqb96t+wCpXHgHYiSo5veTodw5zfaxs6Y
          V0FB7D7AZUoPIkCtR/OIiWVD0KW+Sg9HgcKIWvfwJpqgw66HBMo6j2JE3+V/6Vub4Gglm
          l/R8lUEfecfvB3FHdQQP8xnUhIq9hfs29nqfrz4EkdPWNV4HKtXES+DZ5AgxXXXXSWtGS
          KAmP1ePwJM09HMmqYdbLrAF/SrEzAMuVaqQOxplPVde4J/oQT5Uvr4bsyWw/10=
        - XKeZ3Yv66fazo85C9wzJimiw8XyxekBFsOD2EuhT7+XCEhKgtww37yz0r453EFTutaW0K
          6sskJiKIUegrNRbS/GFWY37Md4j/GQ/RDzECDctNwzhGRIDmwT7JD+kFBcyg3e/178bgR
          3R54zMnH9dkXcDztMSI2YogoH88/hgsa3ZVfoA6M/onmQzGkIqmA/YKIMoc+5eFCoXBQH
          Dc+zCBoL7fkT393Z5ckQ1E03f5znNj/MkR3pPehQVdhbxzBMb7B9KB1xasJ5nZcRwG6Em
          vUCLG3MQ8lrSMkBb0YAps0ke171018KYbqrsRUgoAntzontZDDBndW4jLT88oY+BiHQ4a
          6rViS6UKg9RF8yeM98lhPMrMvKkXoazv4s6+nx9hf84X9ISRa2hXL0Xbl4m4lqmJOqO1a
          Jdd7G73Y3uqwK15uTPkHuwEY5yQpm9xM5o2HHiobc84rSkfK1s0iPZJk3HyMVZqZBQ9aK
          FgzM3zmvTJreoiCOtQ+GMriAFlTOr/nUPSgrmgG2f02MEhKCjAGONDxjRbJ9zhNM2vPi1
          tERIHToWDI1IjM0gawmPyh6McnTcYEN0ukqIYkG/iMpKTL4jOvBig4kTGtAlLglVpM0kz
          zLZXHDk4gwyeuXWJWkKcs04+m0VwwSLr+wwoPoP/8AcVs+Uw+JvO7xjYo5nH9w=
        - Rq8gXa1UsmxNqRRPc7A5LPfxRd9GqvFhxfO5NWmlP/tOrRzwZE+9h7FqGkUTFrA2crIzT
          235njrE4XI/TB9Ij6zWMAXjFbr95RQ9sf8tcXx46eaen6ao40QRD1BkmF2ar2wQhMxIPf
          Erds4J/Tzfoum3mlxhKgM2aunukgI4jVjAKTF8tw1HHZwOBke9b8O6HruaRavdhpKN4Wp
          V8zF/wLb34lEKRlBSdIK/mmKPSU6jW2CMxZsjcr3v33i3WIf3JxB1aqQZriV8Kn8/8mGn
          ZGbn6Km2azp6VEAIZwGpK2aK4cRiNFJdx5a4vQBjlU+7re0mDRq/W4gMbyFD1Q5LrvqyD
          xXmj7i/AEdvi9kQCPPfiz43DbBiZ4J+uoGMagIeTZa5dT0kue+9QxE7mMliDAf6cTdgTB
          FG09pSqKB/pUoOJQ/nuVr61/PXXO796RfxcOXTHHMwQhCgyaGEDzU8+meinKabM7wSLfj
          LA8hIHxbfB0qM+YWjJUm8GeQKUwMKW2ne2WFJPupIzY5F4tsJTU098FICtPeCQaz6RIls
          zwuPh5jRsJedwJidCug/3Cy4Ue381XA0mmCjnRBR0lnua7IhvQ+49LZsyZpv/XakRbwGT
          U1IgFVGaQJwJ0ygsnygItVOdjzdqV8b6cTveaKPfPr96bmDmi4GJbZm2hMvO4s=
        - dJqHIEYC6qgbKL1l4LTsxcYrMOSzmbcZzpKw1d46GELwly7Q1z+KKvK8BfQxyVYmN6AGM
          klAk2c9b/pJhIPxWj1rL/of4MvYmjoGZhhfe/T9FlgdTD/4PypsKFIUudVGDUQJRER2M6
          QR1Re45CLYQAFsT1ZsG5mGJYceRMREG5hrwWDD05NWfTjioehsAkGmgFIGpJ2rmVgo+cW
          QNJ99JROR1mx5NGPsb2fVuUg4kQSZZcb6gv488t91ogVROQFYBuxEOTwI77NqCpKfYCj2
          1syLVkI/5r8XcQb2iZEmb9TXrWq4CjdTYqi2GI+eoJjMQI0AeGKsjOhcJSvv/mp987a8q
          HwHqaelvNu+qEAELXWBo7UWrZvmIB/aDUuucWWXc23kvTkqqO9gN8TFpFAZ6KIOmpK9xU
          w/JYuG9pYnj6SdF+dogbNVtJ47M4CqLfgt/aN2NJ+SA++W/cvrR71vwQvN5pXHW1ktLZm
          86pM2gpKBvKQmk6AwtcpeXatBEX0gZMK4L74JvqbqypLd8v7wcSPtqyB4mDs2IK+oA1Vh
          ZesSTVZr7776A7JI9Pjep21ZDT/ZkMtdvugzFLrLuuZPyxfXnV9Dd44gJSE8A+tAifDNV
          TlZlfayUilq5+sr/Kwx2jGw/LxDTKJ4tOqGFZI8sWKEK3d/Y3ODa1Vq8L8IpV4=
