FROM debian:11 AS base
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update
RUN apt-get -y install\
           snmp snmpd snmptrapd \
           libjson-c-dev \
           libsnmp-dev \
           gcc \
           make
 # Upgrade packages to latest security-patched versions to fix CVEs
RUN apt-get -y install --only-upgrade \
           libssl1.1 \
           libgnutls30 \
           libpng16-16 \
           libfreetype6 \
           perl-base \
           perl-modules-5.32 \
           libc6 \
           libc-bin \
           e2fsprogs \
           libtiff5 \
           libexpat1

WORKDIR /home/trapagent
COPY src/* ./src/
COPY Makefile .
RUN make

FROM base AS deployment-env
WORKDIR /home/trapagent
COPY --from=base /home/trapagent/wrsAlarmMIB .
COPY bootstrap.sh .
RUN chmod 755 ./bootstrap.sh
ENTRYPOINT ["./bootstrap.sh"]
