ARG BASE
FROM ${BASE}
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y install --no-install-recommends \
        snmp \
        snmpd \
        snmptrapd \
        stx-snmp-trap-subagent \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/trapagent
RUN cp /usr/bin/wrsAlarmMIB .
COPY bootstrap.sh .
RUN chmod 755 ./bootstrap.sh

ENTRYPOINT ["./bootstrap.sh"]
