ARG BASE
FROM ${BASE}
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
    apt-get -y install --no-install-recommends \
        snmp \
        snmpd \
        snmptrapd \
        stx-snmp-audit-plugin \
    && rm -rf /var/lib/apt/lists/*

COPY ./mibs/* /usr/share/snmp/mibs/

EXPOSE 161/udp
EXPOSE 162/udp
EXPOSE 705/tcp
CMD /usr/sbin/snmpd $OPTIONDEBUG -f
